version: '3.2'

services:
  cardano:
    image:
      bridgefinance.net/cardano-explorer-docker
    volumes:
      - /home/srv/cardano:/home/cardano/cardano-sl/state-explorer-mainnet
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      resources:
        limits:
          memory: 6G
      restart_policy:
        delay: 2s
        window: 20s

  ada:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/bridgefinance.net-org/bridgefinance.net/build/Dockerfile-ada
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_ada
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_bridgefinance.net

secrets:
  api_bridgefinance.net:
    file: $GOPATH/src/github.com/bridgefinance.net-org/bridgefinance.net/secrets/api_bridgefinance.net.json

volumes: 
  cardano:

networks: 
  scrapers-network:
